ctrl_interface=/var/run/wpa_supplicant
device_name=P2PNode
device_type=1-0050F204-1
p2p_go_intent=15
country=DE

network={
    ssid="DIRECT-MyMesh"
    mode=3
    key_mgmt=WPA-PSK
    psk="yourpassphrase"
    proto=RSN
    pairwise=CCMP
    frequency=2437
}
